spring:
  application:
    name: eventapp
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: eventapp
            client-secret: Cvg0CPwmN9afeXalrEtBt7CoGFemw9BG
            client-name: eventapp
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/event
            token-uri: http://localhost:9090/realms/event/protocol/openid-connect/token

      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/event
server:
  port: 8091


notificationapp:
  url: http://localhost:8092